CREATE TABLE IF NOT EXISTS dim_medicine (
    medicine_id_pk     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_sku       VARCHAR(20) UNIQUE NOT NULL,
    medicine_name      VARCHAR(100) NOT NULL,
    type_description   VARCHAR(100),
    storage_type       VARCHAR(100),
    unit_cost          NUMERIC(18,2),
    expiration_months  INTEGER
);

CREATE INDEX IF NOT EXISTS ix_dim_medicine_sku  ON dim_medicine(medicine_sku);
CREATE INDEX IF NOT EXISTS ix_dim_medicine_type ON dim_medicine(type_description);
