CREATE TABLE IF NOT EXISTS dim_time (
    date_id_pk     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_date      DATE UNIQUE NOT NULL,
    year           INTEGER NOT NULL,
    quarter        INTEGER NOT NULL,
    month          INTEGER NOT NULL,
    month_name     VARCHAR(20),
    day            INTEGER NOT NULL,
    day_of_week    VARCHAR(20)
);

CREATE INDEX IF NOT EXISTS ix_dim_time_date       ON dim_time(full_date);
CREATE INDEX IF NOT EXISTS ix_dim_time_year_month ON dim_time(year, month);
