CREATE TABLE IF NOT EXISTS dim_vendor (
    vendor_id_pk     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_account   VARCHAR(20) UNIQUE NOT NULL,
    vendor_name      VARCHAR(100) NOT NULL,
    vendor_type      VARCHAR(50),
    country_name     VARCHAR(50),
    vendor_status    VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS ix_dim_vendor_account ON dim_vendor(vendor_account);
