-- ==============================================================================
-- 🏥 Data Warehouse Pharmacy Inventory Intelligence — RSUD Ir. Soekarno Sukoharjo
-- File: queries.sql (Revisi Final DDL & Query Analitik)
-- 
-- Penjelasan: File ini berisi seluruh perintah SQL DDL untuk membangun Star Schema
-- (3 Dimensi + 1 Fakta) dengan kolom KPI yang sudah termaterialisasi, diikuti
-- oleh query analitik untuk memanggil ke-6 KPI sesuai standar Permenkes 72/2016.
-- ==============================================================================

-- ==============================================================================
-- PART 1: DDL SCHEMA DEPLOYMENT (Star Schema & Indeks)
-- ==============================================================================

-- 1. Dimensi Obat (dim_medicine)
-- Menyimpan catalog obat, kategori terapi (type_description), dan unit cost (USD).
DROP TABLE IF EXISTS dim_medicine CASCADE;
CREATE TABLE dim_medicine (
    medicine_id_pk     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_sku       VARCHAR(20) UNIQUE NOT NULL,  -- Kode SKU unik dari SIMRS
    medicine_name      VARCHAR(100) NOT NULL,        -- Nama obat
    type_description   VARCHAR(100),                 -- Kategori terapi obat
    storage_type       VARCHAR(100),                 -- Bentuk penyimpanan (Tablet, Ampul, dll)
    unit_cost          NUMERIC(18,2) DEFAULT 0.00,   -- Harga beli satuan (dalam USD)
    expiration_months  INTEGER DEFAULT 0             -- Durasi kedaluwarsa dalam bulan
);

CREATE INDEX ix_dim_medicine_sku  ON dim_medicine(medicine_sku);
CREATE INDEX ix_dim_medicine_type ON dim_medicine(type_description);

-- 2. Dimensi Vendor (dim_vendor)
-- Menyimpan profil vendor pemasok obat.
DROP TABLE IF EXISTS dim_vendor CASCADE;
CREATE TABLE dim_vendor (
    vendor_id_pk     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_account   VARCHAR(20) UNIQUE NOT NULL,   -- Nomor akun vendor unik
    vendor_name      VARCHAR(100) NOT NULL,         -- Nama PT/Vendor
    vendor_type      VARCHAR(50),                  -- Tipe vendor
    country_name     VARCHAR(50),                  -- Negara asal vendor
    vendor_status    VARCHAR(50)                   -- Status keaktifan vendor
);

CREATE INDEX ix_dim_vendor_account ON dim_vendor(vendor_account);

-- 3. Dimensi Waktu (dim_time)
-- Menyimpan kalender temporal untuk aggregasi harian, bulanan, kuartal, dan tahunan.
DROP TABLE IF EXISTS dim_time CASCADE;
CREATE TABLE dim_time (
    date_id_pk     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_date      DATE UNIQUE NOT NULL,          -- Tanggal kalender
    year           INTEGER NOT NULL,              -- Tahun
    quarter        INTEGER NOT NULL,              -- Kuartal (1-4)
    month          INTEGER NOT NULL,              -- Bulan (1-12)
    month_name     VARCHAR(20),                   -- Nama bulan (Januari, dst)
    day            INTEGER NOT NULL,              -- Tanggal (1-31)
    day_of_week    VARCHAR(20)                    -- Nama hari (Senin, dst)
);

CREATE INDEX ix_dim_time_date       ON dim_time(full_date);
CREATE INDEX ix_dim_time_year_month ON dim_time(year, month);

-- 4. Tabel Fakta Inventaris (fact_pharmacy_inventory)
-- Menyimpan kuantitas pergerakan stok harian dan mematerialisasikan 4 metrik KPI.
-- Kolom 'valuasi' dan 'pengeluaran' disimpan dalam USD untuk menjaga rate neutrality.
DROP TABLE IF EXISTS fact_pharmacy_inventory CASCADE;
CREATE TABLE fact_pharmacy_inventory (
    date_id_fk              BIGINT NOT NULL REFERENCES dim_time(date_id_pk),
    medicine_id_fk          BIGINT NOT NULL REFERENCES dim_medicine(medicine_id_pk),
    vendor_id_fk            BIGINT NOT NULL REFERENCES dim_vendor(vendor_id_pk),
    opening_qty             NUMERIC(18,2) NOT NULL DEFAULT 0.00,  -- Saldo awal stok hari itu
    received_qty            NUMERIC(18,2) NOT NULL DEFAULT 0.00,  -- Kuantitas obat masuk
    issued_qty              NUMERIC(18,2) NOT NULL DEFAULT 0.00,  -- Kuantitas obat keluar/pakai
    closed_qty              NUMERIC(18,2) NOT NULL DEFAULT 0.00,  -- Saldo akhir stok hari itu
    stock_availability_pct  NUMERIC(5,2) NOT NULL DEFAULT 0.00,   -- Materialized KPI 1 (%)
    valuasi                 NUMERIC(18,2) NOT NULL DEFAULT 0.00,  -- Materialized KPI 2 (Valuation in USD)
    pengeluaran             NUMERIC(18,2) NOT NULL DEFAULT 0.00,  -- Materialized KPI 3 (Spend in USD)
    wastage_ratio_pct       NUMERIC(5,2) NOT NULL DEFAULT 0.00,   -- Materialized KPI 6 (%)
    turnover_ratio          NUMERIC(18,2) NOT NULL DEFAULT 0.00,  -- Materialized KPI 4
    stock_coverage_days     NUMERIC(18,2) NOT NULL DEFAULT 0.00,  -- Materialized KPI 5
    CONSTRAINT pk_fact_pharmacy_inventory
        PRIMARY KEY (date_id_fk, medicine_id_fk, vendor_id_fk)
);

CREATE INDEX ix_fact_date     ON fact_pharmacy_inventory(date_id_fk);
CREATE INDEX ix_fact_medicine ON fact_pharmacy_inventory(medicine_id_fk);
CREATE INDEX ix_fact_vendor   ON fact_pharmacy_inventory(vendor_id_fk);


-- ==============================================================================
-- PART 2: ANALYTICAL KPI QUERIES (Verifikasi Hasil Implementasi)
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- KATEGORI 1: Performa Ketersediaan Stok
-- ------------------------------------------------------------------------------

-- KPI 1: Persentase Ketersediaan Stok Obat per Jenis Obat
-- Kegunaan: Menampilkan obat dengan tingkat ketersediaan terendah untuk mencegah stockout.
-- Logika: Mengambil kolom materialized 'stock_availability_pct' langsung di grain harian terbaru.
SELECT
    m.medicine_name,
    m.type_description,
    f.stock_availability_pct
FROM fact_pharmacy_inventory f
JOIN dim_medicine m ON f.medicine_id_fk = m.medicine_id_pk
JOIN dim_time     t ON f.date_id_fk     = t.date_id_pk
WHERE t.full_date = (SELECT MAX(full_date) FROM dim_time)
ORDER BY f.stock_availability_pct ASC
LIMIT 10;


-- KPI 2: Valuasi Aset Farmasi per Kategori Terapi (IDR)
-- Kegunaan: Mengetahui nilai nominal modal apotek yang tertanam pada stok obat dalam Rupiah.
-- Logika: Menjumlahkan kolom materialized 'valuasi' (USD) lalu dikalikan nilai tukar Rp15.000.
SELECT
    m.type_description,
    ROUND(SUM(f.valuasi * 15000), 2) AS total_valuasi_idr
FROM fact_pharmacy_inventory f
JOIN dim_medicine m ON f.medicine_id_fk = m.medicine_id_pk
JOIN dim_time     t ON f.date_id_fk     = t.date_id_pk
WHERE t.full_date = (SELECT MAX(full_date) FROM dim_time)
GROUP BY m.type_description
ORDER BY total_valuasi_idr DESC;


-- ------------------------------------------------------------------------------
-- KATEGORI 2: Tren Pengeluaran Historis
-- ------------------------------------------------------------------------------

-- KPI 3: Total Pengeluaran Obat (Kuantitas Bulanan per Kategori Terapi)
-- Kegunaan: Menganalisis kuantitas konsumsi obat bulanan rumah sakit untuk perencanaan pasokan.
-- Logika: Menjumlahkan kolom 'issued_qty' (kuantitas obat keluar) secara bulanan.
SELECT
    t.year,
    t.month_name,
    m.type_description,
    SUM(COALESCE(f.issued_qty, 0)) AS total_pengeluaran
FROM fact_pharmacy_inventory f
JOIN dim_medicine m ON f.medicine_id_fk = m.medicine_id_pk
JOIN dim_time     t ON f.date_id_fk     = t.date_id_pk
GROUP BY t.year, t.month, t.month_name, m.type_description
ORDER BY t.year, t.month, total_pengeluaran DESC
LIMIT 15;


-- ------------------------------------------------------------------------------
-- KATEGORI 3: Efisiensi Pengelolaan Stok
-- ------------------------------------------------------------------------------

-- KPI 4: Inventory Turnover Ratio (ITOR) per Obat
-- Kegunaan: Menilai rasio perputaran stok obat. ITOR rendah menandakan modal mati/obat tidak laku.
-- Logika: Mengambil kolom materialized 'turnover_ratio' langsung di grain harian terbaru.
SELECT
    m.medicine_name,
    m.type_description,
    f.turnover_ratio
FROM fact_pharmacy_inventory f
JOIN dim_medicine m ON f.medicine_id_fk = m.medicine_id_pk
JOIN dim_time     t ON f.date_id_fk     = t.date_id_pk
WHERE t.full_date = (SELECT MAX(full_date) FROM dim_time)
ORDER BY f.turnover_ratio DESC
LIMIT 10;


-- KPI 5: Stock Coverage Days (Tingkat Ketersediaan Hari)
-- Kegunaan: Memprediksi berapa hari sisa stok obat akan bertahan berdasarkan rata-rata pemakaian 30 hari terakhir.
-- Logika: Mengambil kolom materialized 'stock_coverage_days' langsung di grain harian terbaru.
SELECT
    m.medicine_name,
    m.type_description,
    f.stock_coverage_days,
    CASE
        WHEN f.stock_coverage_days > 30 THEN 'GREEN (Aman)'
        WHEN f.stock_coverage_days BETWEEN 14 AND 30 THEN 'YELLOW (Beli Baru)'
        ELSE 'RED (Kritis - Risiko Kosong)'
    END AS status
FROM fact_pharmacy_inventory f
JOIN dim_medicine m ON f.medicine_id_fk = m.medicine_id_pk
JOIN dim_time     t ON f.date_id_fk     = t.date_id_pk
WHERE t.full_date = (SELECT MAX(full_date) FROM dim_time)
  AND f.stock_coverage_days > 0
ORDER BY f.stock_coverage_days ASC
LIMIT 15;


-- ------------------------------------------------------------------------------
-- KATEGORI 4: Manajemen Wastage
-- ------------------------------------------------------------------------------

-- KPI 6: Rasio Inefisiensi Pasokan (Wastage Ratio per Kategori & Vendor)
-- Kegunaan: Mendeteksi inefisiensi pengiriman obat berlebih dari vendor tertentu yang menyebabkan penumpukan stok.
-- Logika: Mengambil kolom materialized 'wastage_ratio_pct' untuk melacak kelebihan suplai harian.
SELECT
    m.type_description,
    v.vendor_name,
    f.wastage_ratio_pct
FROM fact_pharmacy_inventory f
JOIN dim_medicine m ON f.medicine_id_fk = m.medicine_id_pk
JOIN dim_vendor   v ON f.vendor_id_fk   = v.vendor_id_pk
WHERE f.wastage_ratio_pct > 0
ORDER BY f.wastage_ratio_pct DESC
LIMIT 15;
