-- dim med
CREATE TABLE IF NOT EXISTS dim_medicine (
    medicine_id_pk     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_sku       VARCHAR(20) UNIQUE NOT NULL,
    medicine_name      VARCHAR(100) NOT NULL,
    type_description   VARCHAR(100),
    storage_type       VARCHAR(100),
    unit_cost          NUMERIC(18,2),
    expiration_months  INTEGER
);

CREATE INDEX IF NOT EXISTS ix_dim_medicine_sku  ON dim_medicine(medicine_sku);
CREATE INDEX IF NOT EXISTS ix_dim_medicine_type ON dim_medicine(type_description);

--dim vendor
CREATE TABLE IF NOT EXISTS dim_vendor (
    vendor_id_pk     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_account   VARCHAR(20) UNIQUE NOT NULL,
    vendor_name      VARCHAR(100) NOT NULL,
    vendor_type      VARCHAR(50),
    country_name     VARCHAR(50),
    vendor_status    VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS ix_dim_vendor_account ON dim_vendor(vendor_account);


-- dim time
CREATE TABLE IF NOT EXISTS dim_time (
    date_id_pk     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_date      DATE UNIQUE NOT NULL,
    year           INTEGER NOT NULL,
    quarter        INTEGER NOT NULL,
    month          INTEGER NOT NULL,
    month_name     VARCHAR(20),
    day            INTEGER NOT NULL,
    day_of_week    VARCHAR(20)
);

CREATE INDEX IF NOT EXISTS ix_dim_time_date       ON dim_time(full_date);
CREATE INDEX IF NOT EXISTS ix_dim_time_year_month ON dim_time(year, month);


-- fact
CREATE TABLE IF NOT EXISTS fact_pharmacy_inventory (
    date_id_fk      BIGINT NOT NULL REFERENCES dim_time(date_id_pk),
    medicine_id_fk  BIGINT NOT NULL REFERENCES dim_medicine(medicine_id_pk),
    vendor_id_fk    BIGINT NOT NULL REFERENCES dim_vendor(vendor_id_pk),
    opening_qty     NUMERIC(18,2) NOT NULL DEFAULT 0,
    received_qty    NUMERIC(18,2) NOT NULL DEFAULT 0,
    issued_qty      NUMERIC(18,2) NOT NULL DEFAULT 0,
    closed_qty      NUMERIC(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT pk_fact_pharmacy_inventory
        PRIMARY KEY (date_id_fk, medicine_id_fk, vendor_id_fk)
);

CREATE INDEX IF NOT EXISTS ix_fact_date     ON fact_pharmacy_inventory(date_id_fk);
CREATE INDEX IF NOT EXISTS ix_fact_medicine ON fact_pharmacy_inventory(medicine_id_fk);
CREATE INDEX IF NOT EXISTS ix_fact_vendor   ON fact_pharmacy_inventory(vendor_id_fk);
